- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GH_PAT }}
    publish_dir: ./out
    keep_files: false
    force_orphan: true
    publish_branch: gh-pages  # Explicitly set branch name
    user_name: 'github-actions[bot]'
    user_email: 'github-actions[bot]@users.noreply.github.com'